### PR TITLE
Text review and alignment with agreed scope

### LINKED ISSUE #37: Optical Impairments Topology
Add some text describing that the optical impairments topology is out of scope since this draft is assuming that Optical path computation is performed by the O-PNCs.

### PR DESCRIPTION
**Pull request by italobusi**
Proposed updates to the document based on the whole text review for IETF 112

Fix #37

### CODE REVIEW

**Comment by italobusi** [comment]
**[2021-11-23 ACTN POI Call (Slot 1)
](https://github.com/FabioPeruzzini/actn-poi/blob/master/minutes/minutes-2021-11-23.md)**

Review still on-goin (PR in draft status): daily updates are committed when available

Section 2 does not need to be too long and the relevant material for L2/L3 VPN setup could be moved to section 4 (if not already present)

**Comment by italobusi** [comment]
**2021-11-30 ACTN POI Call (Slot 2)**

Do not merge the PR #70 but incorporate the proposed changes in this PR

Agreed to use the term "approach" for describing the three cases of path computation

Clarify what level of abstraction is assumed

Move to section 4 the description of how the topology models are used to discover optical and IP topologies

Add some description and figure on how inter-domain links are discovered

Add some description about the case of intra-domain single-layer IP links (with no undelay optical tunnel)

**Comment by italobusi** [comment]
[**2021-12-21 ACTN POI call (Slot 1)**](https://github.com/FabioPeruzzini/actn-poi/blob/master/minutes/minutes-2021-12-21.md)

Reviewed the latest text changes to section 3 and 4.1

Updated text uploaded on github: https://github.com/FabioPeruzzini/actn-poi/pull/69/commits/a3276380ff8fce68a7757edd606b230bcd1c1e2f

**Comment by italobusi** [comment]
Slides [inter-domain-link-discovery-00.pptx](https://github.com/FabioPeruzzini/actn-poi/files/7970520/inter-domain-link-discovery-00.pptx):

[Uploading inter-domain-link-discovery-00.pptx…]()

**Comment by italobusi** [comment]
This is the file with all the revision marks:
[draft-ietf-teas-actn-poi-applicability - rm.docx](https://github.com/FabioPeruzzini/actn-poi/files/7972798/draft-ietf-teas-actn-poi-applicability.-.rm.docx)

**Comment by jbouqui153** [comment]
Here is my review of the draft with revision marks in the clean version shared. 
[draft-ietf-teas-actn-poi-applicability - JB review complete.docx](https://github.com/FabioPeruzzini/actn-poi/files/8063490/draft-ietf-teas-actn-poi-applicability.-.JB.review.complete.docx)

**Comment by italobusi** [comment]
**[2022-02-15 ACTN POI Call (Slot 1)](https://github.com/FabioPeruzzini/actn-poi/blob/master/minutes/minutes-2022-02-15.md)**

Major comments from Jeff:

1. in section 4.2 the description starts from a reference to a figure with router names but optical nodes have no names and the description becomes more generic. The text should be either generic or just be an example till the end.

Agreement to review the text description

2. we say that the MDSC always sends the explicit path to the P-PNC, but with big domains it may be beneficial to just provide a loose path and leave up to the P-PNC to figure out the detailed path

Major comments from Paolo:
1. section 2.2 should be maintained but rewritten to clarify that SR-TE is used (related to Jeff's comment 2 above)

Agreement is to keep section 2.2 and to align its content with the rest of the document

The key issue is about whether the MDSC needs to always configure an explicit path or whether it could specify a loose path

As discussed in section 2.1.2, with partial summarization the MDSC computes the complete path in the packet layer. This is required for the MDSC to understand whether there is a need or not to setup new optical tunnels and, if needed, which optical tunnels to request to O-PNCs.

However, there is no need for the MDSC to always specify the complete explicit path to the P-PNC when requesting the P-PNC to set the path up. If the MDSC specifies a loose path to the P-PNC, it is possible that the intra-domain path installed by P-PNC is different from the intra-domain path segment computed by the MDSC but, as long as the TE constraints are satisfied, this is acceptable.

Considering for example the SR-TE path between PE13 and PE23, the MDSC can compute the PE13-P15-BR11 - BR21-P24-PE23 path. In this case, the MDSC can request the P-PNC2 to setup the strict BR21-P24-PE23 path or a loose BR21-PE23 path. In the latter case, the P-PNC2 can setup a BR21-BR22-PE23 path instead of the BR21-P24-PE23 path computed by the MDSC.

Bandwidth allocation with RSVP-TE is performed by the routers; with SR-TE bandwidth allocation is not performed by the routers but by a controller. In our scenario, the controller can be either the P-PNC or the MDSC: in the draft it is assumed that it is the P-PNC.

**Comment by italobusi** [comment]
Combined comments from @jbouqui153 , @Paolo-Volpato and @sergiobelotti : [draft-ietf-teas-actn-poi-applicability - JB-PV-SB.docx](https://github.com/FabioPeruzzini/actn-poi/files/8111706/draft-ietf-teas-actn-poi-applicability.-.JB-PV-SB.docx)

Slides describing some link discovery cases updated to address some of these comments:
[inter-domain-link-discovery-03.pptx](https://github.com/FabioPeruzzini/actn-poi/files/8111703/inter-domain-link-discovery-03.pptx)

**Comment by italobusi** [comment]
**2022-02-22 ACTN POI Call (Slot 2)**

See: https://demo.hedgedoc.org/Lt4DCI9dRWe1mFQbPtZaPg

**Comment by Paolo-Volpato** [comment]
> [x] Paolo: to discuss offline via mail some text proposal for section 2.2
[draft-ietf-teas-actn-poi-applicability.-.JB-PV-SB-new2.2.docx](https://github.com/FabioPeruzzini/actn-poi/files/8122913/draft-ietf-teas-actn-poi-applicability.-.JB-PV-SB-new2.2.docx)

**Comment by italobusi** [comment]
> * [x]  Gabriele: to prepare an ASCII version of slides 3, 5, 9 and, optionally, 7 for inclusion, as examples, in the draft
> 

Sent by @ggalimba56 : [ASCII-drawings-for-POI-v1.txt](https://github.com/FabioPeruzzini/actn-poi/files/8161120/ASCII-drawings-for-POI-v1.txt)

**Comment by italobusi** [comment]
[2022-03-01 ACTN POI Call (Slot 1)](https://demo.hedgedoc.org/sRDV7vcNSSeSS11g5-TuAw)

#### Figures for link discovery cases would help

> - [x] Gabriele: to prepare an ASCII version of slides 3, 5, 9 and, optinally, 7 for inclusion, as examples, in the draft

> - [x] Italo: update the draft description referencing the examples in the slides

Text updated in PR#69 to reference the figures in ppt slides

ASCII figures provided by Gabriele:

https://github.com/FabioPeruzzini/actn-poi/files/8161120/ASCII-drawings-for-POI-v1.txt

ASCII figures updated during the call (editorial refinement):

[ASCII-drawings-for-POI-v2.txt](https://github.com/FabioPeruzzini/actn-poi/files/8161143/ASCII-drawings-for-POI-v2.txt)

- [ ] Italo: finalize the ASCII figures and update the draft with the new figures

#### SR-TE bandwidth

> - [ ] Brent: to provide some text for section 4.2.3 about the protection options: to be further discussed whether to place this text in section 4.2.3 or in section 2.2.2

A new open issue #80 has been created (target IETF 114)

#### LLDP: Chassis ID versus System Name TLVs

> - [x] Italo: update the text to clarify that:
>   - routers and optical NEs should report all the relevant LLDP information (including System Name is used)
>   - the encoding of the LLDP information is implementation-specific, but the encoding rules need to be consistent across all the PNCs. The suggestion is to encode the Chassis ID and Port ID since they are mandatory TLVs.

Latest text in PR #69 updated accordingly

#### Explicit path configuration

> - [x] Paolo: to discuss offline via mail some text proposal for section 2.2

Proposal submitted to github: https://github.com/FabioPeruzzini/actn-poi/files/8122913/draft-ietf-teas-actn-poi-applicability.-.JB-PV-SB-new2.2.docx

Text proposal discussed offline and text in PR #69 updated accordingly

#### Who configures IP links: P-PNC, MDSC or either (on a case-by-case)

> - [x] Jeff: get some feedbacks from IP dept

> - [x] Continue discussion of this issue offline

Conclusion from offline discussion:
- Update the draft assuming that the intra-domain IP links are always configured by the P-PNC
- Describe the implications of this assumption:
  - MDSC receives a request to setup a L2/L3 VPN service
  - MDSC understands that in order to fulfill this service requests it needs to setup a new optical tunnel (to support the setup of a new IP link)
  - MDSC requests the O-PNC to setup the optical tunnel
  - After the optical tunnel has been successfully setup, MDSC waits for the P-PNC to configure the new IP link
     - After the new optical tunnel has been setup, the P-PNC may automatically discovers the new adjacency (e.g., through LLDP) and configures the new IP link.
     - Alternatively, the MDSC may configure the new intra-domain Ethernet link and the P-PNC can then configure the new IP link.
  - After the P-PNC has setup the new IP link, the MDSC requests the P-PNC to setup a new SR-TE path or re-route an existing SR-TE path through the new IP link
    - The MDSC will get notified that the new IP link has been setup by the P-PNC by a topology update of the SR-TE topology exposed by the P-PNC
- Discuss this issue during the TEAS WG session at IETF 113 to get feedbacks from the WG
- Track this as a new open issue (*TBD*) in github to be resolved by IETF 114, taking into account the feedbacks from IETF 113 discussion
- The configuration of the inter-domain IP links does not involve any multi-layer coordination and therefore can be considered outside the scope of this document

- [ ] Italo: Update the text to align with this conclusion

- [ ] Italo: Create a new open issue to track the discussion at IETF 113

#### Terminology: router port versus Ethernet interface

Summary of offline discussion:
- Use the term “port” to represent the physical entity and the term “interface” to entities which can be logical
- Describe the router configuration (if needed) as:
  - without LAG: : an Ethernet port (physical) supporting an Ethernet interface supporting an IP interface
  - with LAG: a set of Ethernet ports (physical) each one supporting an Ethernet interface and all supporting a LAG interface (logical) supporting an IP interface (logical)
- Describe the optical NE configuration (if needed) as:
  - an Ethernet port (physical) supporting an Ethernet interface
- A link is an association between two interfaces that can exchange traffic directly
  - An Ethernet link is a link between two Ethernet interfaces
  - An IP link is a link between two IP interfaces
- Define the following links:
  - a cross-layer (Ethernet) link is an Ethernet link between an Ethernet interface on the router and an Ethernet interface on the optical NE, supported by a fiber (cable) between the corresponding Ethernet ports on these router and optical NE;
  - an intra-domain single-layer Ethernet link is a link between two Ethernet interfaces on adjacent routers, supported by a fiber (cable) between the corresponding Ethernet ports on these adjacent routers
  - an intra-domain single-layer IP link is a link between two IP interfaces on adjacent routers, supported by an intra-domain single-layer Ethernet link
  - an inter-domain single-layer Ethernet link is an Ethernet link between two Ethernet interfaces on adjacent routers, which belong to different P-PNC domains, supported by a fiber (cable) between the corresponding Ethernet ports on these adjacent routers
  - an inter-domain single-layer IP link is a link between two IP interfaces on adjacent routers, which belong to different P-PNC domains, supported by an inter-domain single-layer Ethernet link
  - an intra-domain multi-layer ETH link is a link between two Ethernet interfaces supported by two cross-layer links and an optical tunnel
  - an intra-domain multi-layer IP link is a link between two IP interfaces, supported by an intra-domain multi-layer ETH link
- Consider the concept of a LAG link supported by multiple ETH links (to be discussed whether only intra-domain single-layer or also of other types when LAG scenarios are added to the draft)

- [ ] Italo: include these definitions in the draft

#### Additional comments

> - [x] Italo: Update the reference to L3NM draft with a reference to RFC9182

> - [ ] Italo: check with TEAS experts about L3-TE Topo for SR-TE

Latest text in PR #69 updated accordingly

- [ ] Italo: update section 2.3 for consistency with section 2.2

- [ ] Italo: renumber section 4.1 and 4.2 as sections 4 and 5 (leaving room for some sub-sections)

- [ ] Italo: move around some text in section 4.2 to improve the flow of the description

**Comment by italobusi** [comment]
This is the version tracking all the changes agreed during the 2022-03-01 ACTN POI weekly call to address the review comments from Jeff, Paolo and Sergio:

[draft-ietf-teas-actn-poi-applicability@2022-03-01.docx](https://github.com/FabioPeruzzini/actn-poi/files/8161286/draft-ietf-teas-actn-poi-applicability%402022-03-01.docx)

For the next updates (to finalize the resolution of all the comments) all these changes will be accepted and revision bars will mark the difference to this version

**Comment by italobusi** [comment]
> #### Figures for link discovery cases would help
> 
> * [x]  Italo: finalize the ASCII figures and update the draft with the new figures

Done in https://github.com/FabioPeruzzini/actn-poi/pull/69/commits/7040521c20b31da96346d4ef32c8a5cfea1d62e6

> #### Who configures IP links: P-PNC, MDSC or either (on a case-by-case)
> 
> * [x]  Italo: Update the text to align with this conclusion
> 

Done in https://github.com/FabioPeruzzini/actn-poi/pull/69/commits/7040521c20b31da96346d4ef32c8a5cfea1d62e6

> #### Terminology: router port versus Ethernet interface
> 
> * [X]  Italo: include these definitions in the draft
> 

Done in https://github.com/FabioPeruzzini/actn-poi/pull/69/commits/7040521c20b31da96346d4ef32c8a5cfea1d62e6

> #### Additional comments
> 
> * [x]  Italo: update section 2.3 for consistency with section 2.2
> * [x]  Italo: renumber section 4.1 and 4.2 as sections 4 and 5 (leaving room for some sub-sections)
> * [x]  Italo: move around some text in section 4.2 to improve the flow of the description

Done in https://github.com/FabioPeruzzini/actn-poi/pull/69/commits/7040521c20b31da96346d4ef32c8a5cfea1d62e6

**Pull request merged**
