### PR TITLE
Added text for Inventory

### PR DESCRIPTION
**Pull request by italobusi**
Added text for Inventory analysis (requirements and gaps)

Closing #16 

Co-authored-by: jbouqui153 <53513497+jbouqui153@users.noreply.github.com>

### CODE REVIEW

**Review by anton1688 — COMMENTED** [review]
minor editorial - 
* 4.1 index heading needs to be updated per the new heading for 4.1.
* 4.1.3 to be added in index

the summary statement of the additions (paraphrasing) -  inventory is needed, gaps exist, but outside the scope of this document. 

should we add some possibilities we considered part of our meeting? e.g., 
* schema-mount of device-level schema sub-trees (openconfig or proprietary.) to well defined mount-point/s e.g., ietf-network:node, ietf-network-topology:termination-point. this could probably be found as "too open" to interpretation.
* a new set of network level grouping-uses parings/augmentations to the ietf-network model which will be known as the ietf-network-inventory to try and handle how equipment is reported in a generalised model
* other?

**Comment by italobusi** [comment]
> minor editorial -
> 
> * 4.1 index heading needs to be updated per the new heading for 4.1.
> * 4.1.3 to be added in index
> 

Fixed with https://github.com/FabioPeruzzini/actn-poi/pull/43/commits/4dd0cbc700d84474d860ef4af0f183742d52e76b

> the summary statement of the additions (paraphrasing) - inventory is needed, gaps exist, but outside the scope of this document.
> 

Correct

> should we add some possibilities we considered part of our meeting? e.g.,
> 
> * schema-mount of device-level schema sub-trees (openconfig or proprietary.) to well defined mount-point/s e.g., ietf-network:node, ietf-network-topology:termination-point. this could probably be found as "too open" to interpretation.
> * a new set of network level grouping-uses parings/augmentations to the ietf-network model which will be known as the ietf-network-inventory to try and handle how equipment is reported in a generalised model
> * other?

Addressing the gaps is outside the scope of this document so no need to describe the alternative solutions under investigation within the draft

**Review by Paolo-Volpato — APPROVED** [review]
I think the current text is fine. A future version may provide more details on how the inventory is built from the notifications exchanged at the MPI

**Review by sergiobelotti — APPROVED** [review]

**Review by FabioPeruzzini — APPROVED** [review]

**Comment by oscargdd** [comment]
In my view it would be good to discuss and narrow down the scope of the Inventory, just to avoid the "boiling the ocean problem". I guess we need to focus the scope in the use cases of Packet over Optical, right? We can say that the "inventory" is device information that is used by the different management layers. In the context of PoI, the inventory information can complement the topology views and facilitate the IP-Optical view.

**Comment by italobusi** [comment]
> boiling the ocean problem

I agree that we should try to avoid boiling the ocean with the inventory YANG model

**Comment by italobusi** [comment]
> In my view it would be good to discuss and narrow down the scope of the Inventory, just to avoid the "boiling the ocean problem". I guess we need to focus the scope in the use cases of Packet over Optical, right? We can say that the "inventory" is device information that is used by the different management layers. In the context of PoI, the inventory information can complement the topology views and facilitate the IP-Optical view.

Addressed with https://github.com/FabioPeruzzini/actn-poi/pull/43/commits/9b0c5e8f236915da1acc4d5603ff6cc40404e02f discussed during the 2021-04-20 call

**Pull request merged**
